### ISSUE TITLE
Support for @codekit-prepend/append

### ISSUE THREAD

**Issue by johnsardine** [fatso83/grunt-codekit#15]
Hello,

I found in your blog and in the commit history that you added and then removed support for @codekit-prepend/append. Can you tell me a bit more about that change? Do you have any recommendation on how to handle those imports in grunt?

Thank you

**Comment by fatso83** [comment]
This was my answer to a guy that asked me on email:

>  I removed support for javascript concatenation in version 1.0 as I did not see anyone use it. Focusing on just the Kit language - leaving out js, ruby, etc - also simplified development/maintenance. I was thinking about splitting it out into a separate plugin project based on my little file-builder, but never got around to doing it.
> 
> But the old version 0.4 is still around, and you can use that until I get some time on my hands to hack out a new grunt-plugin. Just set the version "grunt-codekit": "0.4.1". That should work.

Does that help? I might just create a small codekit-js-concat grunt plugin to do this, but it will be very simple. I just haven't seen the demand.

**Comment by fatso83** [comment]
And another reply from this summer with more info
 
> You absolutely read that correctly, as I in the beginning was thinking of making a kind of swiss-knife style "compile everything CodeKit can" type plugin :-) "Grunt-Codekit - your one-stop solution for dropping codekit" ...
> 
> But ... that kind of thinking goes against how the Node community makes modules: do one thing and do it well. (some take it to the extreme, though)
> 
> So when I met some resistance in my code, and seeing that not many seemed to care about that functionality, I ended up removing support for js-concatenation to simplify the code. From its fancy beginnings, embedding python scripts and whatnot, the grunt plugin is currently little more than a wrapper around "node-kit".
> 
> But all is not lost ;)
> 
> I used quite some time tinkering to get the javascript bit working, and all of that code is split into its own module: node-file-builder. Yup, crap name, but reflects my idea of aiming for it to build everything. It basically wraps an angular app called PrePros (a CodeKit clone) and makes it do the actual work. Kind of a dirty/elegant hack, but it works. You can fork it, rename it, or use it as you like. 
> 
> I would like to redo this module in a month or so, ripping out the main code from PrePros, but I need to deliver a master thesis first!
> 
> So to sum up:
> 
> Gulp:
> - use node-kit directly to convert kit-files. Dead easy synchronous code.
> - use node-file-builder to concatenate javascript using your @codekit directives
> 
> Grunt alternative 1
> - use the latest version with built-in js support: grunt-codekit@0.4.1
> Of course, that does not use the latest version of node-kit, so you might have some whitespace differences in the output

> Grunt alternative 2
> - use grunt-codekit for kit-file compilation
> - wait a month for me to make a grunt-codekit-js-directives module 
> 
> ... or roll your own! - it's dead easy (grunt-codekit was my first attempt). 
> You can basically fork the 0.4 tag, which contains everything you need, and rip out html-compilation and you

**Comment by johnsardine** [comment]
Thank you for your clarification. I would find it useful, since currently Im trying to make a project available for codekit users and for those who don't/can't use. Your work has been useful, thank you. Maybe I'll end up building the js module.
