### ISSUE TITLE
Any way to use Babel and ES6?

### ISSUE THREAD

**Issue by leojh** [fatso83/grunt-codekit#16]
Would like to know if there is any way to use this alongside babel in order to support ES6+ ?

**Comment by fatso83** [comment]
I really have no idea what you mean. This does not have anything to do with javascript, so why do you ask?

**Comment by fatso83** [comment]
Reference: [The Kit language](https://incident57.com/codekit/help.html#kit)

Closing. Feel free to reopen if you actually have a problem you are unable to solve :-)
